### ISSUE TITLE
use and import cli.yml file to finish project-1 failed

### ISSUE THREAD

**Issue by PhzCode** [pingcap/talent-plan#375]
## General Question
The sourse in github using clap crate is coding in the kvs.rs file. However, I use the cli.yml to do it, and I can not pass some test cases.

## cli.yml file
```
name: project-1
version: "1.0"
author: *
about: get some args to do something
args:
    - INPUT:
        help: the flag to input
        required: true
        index: 1
    - V:
        short: V
        multiple: false
        help: show the version
subcommands:
    - set:
        about: to set the key-value with the input
        version: "1.0"
        author: *
        args:
            - key:
                index: 1
                help: the key is needed.
                required: true
            - value:
                index: 2
                help: the value is needed.
                required: true
    - get:
        about: to get the value by the key
        version: "1.0"
        author: *
        args:
            - key:
                index: 1
                help: the key is needed.
                required: true
    - rm:
        about: to remove the key-value by the key
        version: "1.0"
        author: *
        args:
            - key:
                index: 1
                help: the key is needed.
                required: true
    
```
## kvs.rs file
```
#[macro_use]
extern crate clap;
use clap::App;
use std::process::exit;

fn main() {

    let yaml = load_yaml!("cli.yml");
    let matches = App::from_yaml(yaml).get_matches();

    if matches.is_present("V") {
        println!(env!("CARGO_PKG_VERSION"));
    }

    match matches.subcommand() {
        ("set", Some(_matches)) => {
            eprintln!("unimplemented");
            exit(1);
        }
        ("get", Some(_matches)) => {
            eprintln!("unimplemented");
            exit(1);
        }
        ("rm", Some(_matches)) => {
            eprintln!("unimplemented");
            exit(1);
        }
        _ => unreachable!(),
    }
}
```
## the test result
```
running 13 tests
test cli_no_args ... ok
test cli_invalid_subcommand ... ok
test get_non_existent_value ... ok
test cli_get ... FAILED
test get_stored_value ... ok
test overwrite_value ... ok
test remove_key ... ok
test cli_rm ... FAILED
test cli_set ... FAILED
test cli_invalid_get ... ok
test cli_invalid_rm ... ok
test cli_version ... FAILED
test cli_invalid_set ... ok
```
